export let projectList = [
    // {name: '', deployed: true/false, collaborative: true/false, focus: '', repo: '', link: '', img: ''},
    // personal projects
    {name: 'C# CatWorx Badge Generator', deployed: false, collaborative: false, focus: 'C#, ASP.NET Core', repo: 'https://github.com/TOVTC/csharp-.net-CatWorx', img: 'csharp-catworx'},
    {name: 'Just Tech News', deployed: true, collaborative: false, focus: 'Java Full Stack MVC', repo: 'https://github.com/TOVTC/tech-news-java-api', link: 'https://cc-java-api-777.herokuapp.com/', img: 'java-tech-news'},
    {name: 'Java Employee Tracker', deployed: false, collaborative: false, focus: 'Spring Boot API', repo: 'https://github.com/TOVTC/java-spring-employee-api', img: 'java-employee-api'},
    {name: 'Hello, User!', deployed: false, collaborative: false, focus: 'Java API', repo: 'https://github.com/TOVTC/spring-java-greeting-api', img: 'java-hello-user'},
    // bootcamp challenges
    {name: 'Locum', deployed: true, collaborative: true, focus: 'Full Stack React SPA', repo: 'https://github.com/TOVTC/Locum-project-three', link: 'https://locum-staffing.herokuapp.com/', img: 'locum'},
    {name: 'React Portfolio', deployed: true, collaborative: false, focus: 'React SPA', repo: 'https://github.com/TOVTC/react-portfolio-scscbc-challenge', link: 'https://tovtc.github.io/react-portfolio-scscbc-challenge/', img: 'react-portfolio'},
    {name: 'Budget Tracker', deployed: true, collaborative: false, focus: 'Progressive Web Applications', repo: 'https://github.com/TOVTC/budget-tracker-scscbc-challenge', link: 'https://gorgeous-canyonlands-37122.herokuapp.com/', img: 'budget-tracker'},
    {name: 'Social Network API', deployed: false, collaborative: false, focus: 'NoSQL', repo: 'https://github.com/TOVTC/social-network-challenge-scscbc', img: 'social-network-api'},
    {name: 'Fermata', deployed: true, collaborative: true, focus: 'Full Stack MVC', repo: 'https://github.com/TOVTC/Fermata-project-two', link: 'https://experience-fermata.herokuapp.com/home', img: 'fermata'},
    {name: 'E-Commerce Backend', deployed: false, collaborative: false, focus: 'Object Relational Mapping', repo: 'https://github.com/TOVTC/e-commerce-backend-scscbc-challenge', img: 'e-commerce'},
    {name: 'Employee Tracker', deployed: false, collaborative: false, focus: 'MySQL', repo: 'https://github.com/TOVTC/employee-tracker-scscbc-challenge', img: 'employee-tracker'},
    {name: 'Note Taker', deployed: true, collaborative: false, focus: 'Express Server', repo: 'https://github.com/TOVTC/note-taker-scscbc-challenge', link: 'https://stark-sea-34689.herokuapp.com/', img: 'note-taker'},
    {name: 'Team Profile Generator', deployed: false, collaborative: false, focus: 'Object Oriented Programming', repo: 'https://github.com/TOVTC/team-profile-generator-scscbc-challenge', img: 'team-generator'},
    {name: 'README Generator', deployed: false, collaborative: false, focus: 'Node', repo: 'https://github.com/TOVTC/readme-generator-scscbc-challenge', img: 'readme-generator'},
    {name: 'WeathCon', deployed: true, collaborative: true, focus: 'Interactive Frontend', repo: 'https://github.com/TOVTC/WeathCon-project-one', link: 'https://scscbc-projects2022.github.io/WeathCon-project-one/', img: 'weathcon'},
    {name: 'Weather Dashboard', deployed: true, collaborative: false, focus: 'Server-Side APIs', repo: 'https://github.com/TOVTC/weather-dashboard-scscbc-challenge', link: 'https://tovtc.github.io/weather-dashboard-scscbc-challenge/', img: 'weather-dashboard'},
    {name: 'Workday Scheduler', deployed: true, collaborative: false, focus: 'Third-Party APIs', repo: 'https://github.com/TOVTC/scheduler-scscbc-challenge', link: 'https://tovtc.github.io/scheduler-scscbc-challenge/', img: 'scheduler'},
    {name: 'Code Quiz', deployed: true, collaborative: false, focus: 'Web APIs', repo: 'https://github.com/TOVTC/code-quiz-scscbc-challenge', link: 'https://tovtc.github.io/code-quiz-scscbc-challenge/', img: 'coding-quiz'},
    {name: 'Password Generator', deployed: true, collaborative: false, focus: 'JavaScript', repo: 'https://github.com/TOVTC/password-generator-scscbc-challenge', link: 'https://tovtc.github.io/password-generator-scscbc-challenge/', img: 'password-generator'},
    {name: 'Personal Portfolio', deployed: true, collaborative: false, focus: 'CSS Flexbox', repo: 'https://github.com/TOVTC/portfolio-scscbc-challenge', link: 'https://tovtc.github.io/portfolio-scscbc-challenge/', img: 'portfolio'},
    {name: 'Horiseon', deployed: true, collaborative: false, focus: 'Accessible Code Refactor', repo: 'https://github.com/TOVTC/horiseon-scscbc-challenge', link: 'https://tovtc.github.io/horiseon-scscbc-challenge/', img: 'horiseon'},
]